In [1]:
numbers = [10, 20, 40, 40, 30]
unique_numbers = list(set(numbers))
unique_numbers.sort()
print(unique_numbers[-2])

30


In [2]:
import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
a = 0.1
b =0.2
c = (a==b)
print(c)


False


In [4]:
a = 0.1 
b = 0.2

sum = a + b
print(sum)

0.30000000000000004


In [5]:
import numpy as np

a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [6]:
a = np.array([9.2,5.8,7.8,5.7])
print(a)

[9.2 5.8 7.8 5.7]


In [7]:
a = np.array(["Apple","Mango","Banana"])

print(a)


['Apple' 'Mango' 'Banana']


In [8]:
a = np.array([10,20,30])
print(a)

[10 20 30]


In [9]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [12]:
a = np.array([[1,2],[3,4]])
print(a.size)

4


In [13]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a.size)
print(a.shape)
print(a)


4
(2, 2)
[[1 2]
 [3 4]]


In [14]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
a = np.eye(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
import numpy as np

a = np.ones((3, 4))

print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
import numpy as np

a = np.arange(1,11)

print (a)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
a = np.arange(1,20,2)

print(a)


[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
b = a.reshape(3,4)

print(b)

<class 'ValueError'>: cannot reshape array of size 10 into shape (3,4)

In [20]:
#convert matrix into row

a = np.array([[1,2],[3,4]])

print(a.flatten())

[1 2 3 4]


In [21]:
#indexing

a = np.array([10,20,30,40])

print(a[0])

10


In [22]:
#indexing

a = np.array([10,20,30,40])

print(a[3])

40


In [23]:
#indexing

a = np.array([10,20,30,40])

print(a[-2])

30


In [24]:
#indexing

a = np.array([40,10,20,45])
sort = np.sort(a)

print(sort)

print(a[-2])

[10 20 40 45]
20


In [25]:
#indexing

a = np.array([40,10,20,45])
sort = np.sort(a)

print(sort)

print(a[-2])

[10 20 40 45]
20


In [26]:
# subsstration of array
a
a = np.array([10,20,30])

b = np.array([1,2,3])

print(a-b)

[ 9 18 27]


In [27]:
# multiplication of array

a = np.array([10,20,30])

b = np.array([1,2,3])

print(a*b)

[10 40 90]


In [28]:
# division of array

a = np.array([10,20,30])

b = np.array([1,2,3])

print(a/b)

[10. 10. 10.]


In [29]:
# square of array

a = np.array([10,20,30])

b = np.array([1,2,3])

print(a**b)

[   10   400 27000]


In [30]:
# modulus of array

a = np.array([10,20,30])

b = np.array([1,2,3])

print(a%b)

[0 0 0]


In [31]:
#create a 4*4 array of zeros

a = np.zeros([4,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
# create a 3*3 identity matrix

a = np.ones([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
# find the shape of 2*5 array

a = np.shape([2,5])

print(a)

(2,)


In [34]:
# reshape an array of 12 elements into a 3*4 matrix

a = np.arange(12)
b = a.reshape([3,4])
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
# find the max and min value in an array

a = np.array([20,30,45,40])
print(a.max())
print(a.min())


45
20


In [36]:
# clalulate the mean median and standard deviaction

a = np.array([12,18,25,30,45])
print(a.mean())
print(np.median(a))
print(np.std(a))

26.0
25.0
11.29601699715435


In [37]:
# generate 10 random integer betwen 1 to 100

import random
for i in range(10):
    print(random.randint(1,100))

31
78
13
79
47
83
45
91
90
1
